package the.easyannouncer.impl;

public enum Message{
	RELOAD,
	PLAYER_TOGGLE_ANNOUNCE,
	PLAYER_TOGGLE_ANNOUNCE_WRONG_INPUT,
	COMMAND_NOT_FOUND,
	PLACEHOLDER_TRUE,
	PLACEHOLDER_FALSE,
	PLACEHOLDER_NULL,
	PREFIX
}
